### ISSUE TITLE
'NoneType' object is not callable Error with Django 2.0

### ISSUE THREAD

**Issue by Arlington1985** [ibmdb/python-ibmdb-django#24]
Returning the folling error while executing `python manage.py test`

`Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/db/models/base.py", line 114, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/db/models/base.py", line 315, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/db/models/options.py", line 205, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/db/utils.py", line 203, in __getitem__
    conn = backend.DatabaseWrapper(db, alias)
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/ibm_db_django/base.py", line 155, in __init__
    super( DatabaseWrapper, self ).__init__( *args )
  File "/home/rovshan/development/IBM/datastage_cmdb/venv/lib/python3.6/site-packages/django/db/backends/base/base.py", line 101, in __init__
    self.client = self.client_class(self)
TypeError: 'NoneType' object is not callable
`
I am using **python 3.6**
Where is installed versions:

_Django            2.0.6  
ibm-db            2.0.8a0
ibm-db-django     1.1.1.2_

My `settings.py`

````
"""
Django settings for datastage_cmdb project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9h(gozcmktl8c)37ojlf84mwrr_5=j03(#s-v72f8zul)4%!(6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #DB2 specific
#    'django.contrib.flatpages',
#    'django.contrib.redirects',
#    'django.contrib.comments',
     

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'datastage_cmdb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'datastage_cmdb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE' : 'ibm_db_django',
        'HOST' : 'dashdb-entry-yp-lon02-01.services.eu-gb.bluemix.net',
        'PORT' : '50000',
        'NAME' : 'BLUDB',
        'USER' : 'fake_user',
        'PASSWORD' : 'fake_password',
        'PCONNECT' : True,
    }
}
DATABASE_ENGINE = 'ibm_db_django'


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
````

**Comment by hemlatabhatt** [comment]
@Arlington1985 , Please update to the latest release by pip install ibm_db_django==1.2.0.0 and re-try. Some issues are addressed in the new release. Please revert if you still face the issue.
