### ISSUE TITLE
python django connect to Db2 failed with ibm_db_django

### ISSUE THREAD

**Issue by anikikong** [ibmdb/python-ibmdb-django#37]
python django connect to Db2 failed with ibm_db_django:

D:\Dproject\Db2test>python manage.py test
Wants to create test495b as test database. Type yes to create it else type nono
Wants to use TEST as test database, Type yes to use it as test database or no to exityes
Operations to perform:
Apply all migrations: admin, auth, contenttypes, flatpages, myapp, redirects, sessions, sites
Running migrations:
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_dbi.py", line 1258, in _execute_helper
return_value = ibm_db.execute(self.stmt_handler, parameters)
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 83, in _execute
return self.cursor.execute(sql)
File "C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_django\pybase.py", line 207, in execute
return super( DB2CursorWrapper, self ).execute( operation, parameters )
File "C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_dbi.py", line 1356, in execute
self._execute_helper(parameters)
File "C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_dbi.py", line 1268, in _execute_helper
raise self.messages[len(self.messages) - 1]
ibm_db_dbi.Error: ibm_db_dbi::Error: Exception()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "manage.py", line 15, in <module>
execute_from_command_line(sys.argv)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
utility.execute()
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\commands\test.py", line 26, in run_from_argv
super().run_from_argv(argv)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
self.execute(*args, **cmd_options)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\base.py", line 353, in execute
output = self.handle(*args, **options)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\commands\test.py", line 56, in handle
failures = test_runner.run_tests(test_labels)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\test\runner.py", line 604, in run_tests
old_config = self.setup_databases()
File "C:\ProgramData\Anaconda3\lib\site-packages\django\test\runner.py", line 551, in setup_databases
self.parallel, **kwargs
File "C:\ProgramData\Anaconda3\lib\site-packages\django\test\utils.py", line 174, in setup_databases
serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
File "C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_django\creation.py", line 255, in create_test_db
call_command( 'migrate', database = self.connection.alias, verbosity = verbosity, interactive = False)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 148, in call_command
return command.execute(*args, **defaults)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\base.py", line 353, in execute
output = self.handle(*args, **options)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\base.py", line 83, in wrapped
res = handle_func(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\management\commands\migrate.py", line 203, in handle
fake_initial=fake_initial,
File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\migrations\executor.py", line 91, in migrate
self.recorder.ensure_schema()
File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\migrations\recorder.py", line 55, in ensure_schema
editor.create_model(self.Migration)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\backends\base\schema.py", line 312, in create_model
self.execute(sql, params or None)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\backends\base\schema.py", line 133, in execute
cursor.execute(sql, params)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 68, in execute
return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
return executor(sql, params, many, context)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
return self.cursor.execute(sql, params)
File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\utils.py", line 89, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "C:\ProgramData\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 83, in _execute
return self.cursor.execute(sql)
File "C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_django\pybase.py", line 207, in execute
return super( DB2CursorWrapper, self ).execute( operation, parameters )
File "C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_dbi.py", line 1356, in execute
self._execute_helper(parameters)
File "C:\ProgramData\Anaconda3\lib\site-packages\ibm_db_dbi.py", line 1268, in _execute_helper
raise self.messages[len(self.messages) - 1]
django.db.utils.Error: Exception()

D:\Dproject\Db2test>pip show django
Name: Django
Version: 2.1.3
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: https://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD
Location: c:\programdata\anaconda3\lib\site-packages
Requires: pytz
Required-by:

D:\Dproject\Db2test>pip show ibm_db
Name: ibm-db
Version: 2.0.9
Summary: Python DBI driver for DB2 (LUW, zOS, i5) and IDS
Home-page: http://pypi.python.org/pypi/ibm_db/
Author: IBM Application Development Team
Author-email: opendev@us.ibm.com
License: Apache License 2.0
Location: c:\programdata\anaconda3\lib\site-packages
Requires:
Required-by: ibm-db-sa, ibm-db-django

D:\Dproject\Db2test>pip show ibm_db_django
Name: ibm-db-django
Version: 1.2.0.0
Summary: DB2 support for Django framework.
Home-page: http://pypi.python.org/pypi/ibm_db_django/
Author: IBM Application Development Team
Author-email: opendev@us.ibm.com, ibm_db@googlegroups.com
License: Apache License 2.0
Location: c:\programdata\anaconda3\lib\site-packages
Requires: ibm-db, django
Required-by:

D:\Dproject\Db2test>db2level
DB21085I 此实例或安装（适用的实例名："DB2"）使用 "64" 位和级别标识为 "0609010E"
的 DB2 代码发行版 "SQL10058"。
参考标记为 "DB2 v10.5.800.381"、"s160901" 和 "IP24000"，修订包为 "8"。
产品使用 DB2 副本名 "DB2COPY1" 安装在 "D:\IBM\SQLLIB" 中

**Comment by sujan08** [comment]
Hi ,

Thanks for the update and steps, will update

This is my test steps. I don't know what model class files you need. Can you be more specific?

In case of nix the steps will be like: {{{ $ django-admin.py startproject myproj $ cd myproj $ vi settings.py }}}
The settings.py will be like (after adding DB2 properties): {{{ DATABASES = { 'default': { 'ENGINE' : 'ibm_db_django', 'NAME' : 'mydb', 'USER' : 'db2inst1', 'PASSWORD' : 'ibmdb2', 'HOST' : 'localhost', 'PORT' : '50000', 'PCONNECT' : True, #‌Optional property, default is false } } }}}

To enable DB2 support you need to set value of DATABASE_ENGINE to 'ibm_db_django' in settings.py.
In the tuple INSTALLED_APPS in settings.py add the following lines: {{{ 'django.contrib.flatpages', 'django.contrib.redirects', 'django.contrib.comments', 'django.contrib.admin', }}}
Next step is to run a simple test suite. To do this just execute following command in the project we created earlier: {{{ $ python manage.py test #‌for Django-1.5.x or older $ Python manage.py test django.contrib.auth #‌For Django-1.6.x onwards, since test discovery behavior have changed }}}

Thanks
Sujan

**Comment by anikikong** [comment]
After deleted  USE_TZ=True , it worked
